name: flutter_example
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.12.0+2
  uuid: ^3.0.3
  flutter_dialogflow: ^0.1.3
  flutter_tindercard: 0.2.0
  image_picker: ^0.6.7+22
  universal_html: ^1.2.3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 3.5.1
  json_annotation: 3.1.1
  build_runner: ^1.11.5
  #flutter pub run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "assets/white.png"
  adaptive_icon_foreground: "assets/logo.png"



flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/femaleNames.txt
    - assets/maleNames.txt
    - assets/ProfilePlaceholder.jfif
